# Generated by Django 4.2.7 on 2023-11-29 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgmtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 8, 8, 19, 642904)),
        ),
    ]
