# Generated by Django 4.2.7 on 2023-12-28 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgmtApp', '0002_alter_student_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 8, 15, 43, 943356)),
        ),
    ]
